# frozen_string_literal: true

source 'https://rubygems.org'

## keep in case we need custom packages again
# source 'https://rubygems.pkg.github.com/solarwinds' do
# end

gem 'opentelemetry-exporter-otlp', '0.29.0'
gem 'opentelemetry-exporter-otlp-metrics', '0.1.0'
gem 'solarwinds_apm', '6.1.0'
