# frozen_string_literal: true

source 'https://rubygems.org'

source 'https://rubygems.pkg.github.com/solarwinds' do
  gem 'opentelemetry-exporter-otlp', '0.26.1'
  gem 'opentelemetry-metrics-api', '0.0.1'
  gem 'opentelemetry-metrics-sdk', '0.0.1'
end

gem 'solarwinds_apm', '6.0.1'
