require: 
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: '3.0'
  NewCops: enable
  Exclude:
    - 'sample_start.rb'

Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Naming/MethodName:
  Exclude:
    - 'lib/solarwinds_apm/noop/*.rb'
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/ClassVars:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Naming/VariableNumber:
  Exclude:
    - 'gemfiles/*.gemfile'
Metrics/BlockNesting:
  Exclude:
    - 'lib/solarwinds_apm.rb'
    - 'lib/solarwinds_apm/support.rb'
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'test/api/custom_instrumentation_test.rb'
