FROM amazonlinux:latest

ARG BUNDLE_RUBYGEMS__PKG__GITHUB__COM
ENV LAMBDA_TASK_ROOT=/fake_lambda_task_root/

RUN mkdir /build
COPY . /build

# install ruby 3.2
RUN yum update && yum install -y ruby-devel gcc-c++ make tar openssl-devel git zlib-devel
RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv \
        && git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build \
        && git clone https://github.com/rbenv/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems \
        && echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.profile \
        && echo 'eval "$(rbenv init -)"' >> ~/.profile \
        && echo 'eval "$(rbenv init -)"' >> ~/.bashrc \
        && echo 'bundler' > ~/.rbenv/default-gems

WORKDIR /build/layer
RUN bundle config set --local path 'ruby'

RUN ls | grep solarwinds_apm-*.gem > gem_file.txt 2>/dev/null || true
RUN export gem_file=$(cat gem_file.txt) && \
    if [ -f "$gem_file" ]; then \
        echo "$gem_file exists."; \
        sed -i '$ s/^/#/' /build/layer/Gemfile; \
        bundle update; \
        bundle exec gem install $gem_file; \
    else \
        bundle update; \
    fi

RUN rm /build/layer/ruby/ruby/3.2.0/cache/* && rm -rf /build/layer/ruby/ruby/3.2.0/doc/*

WORKDIR /build/layer/ruby/ruby
RUN zip -qr gems-3.2.0.zip 3.2.0/

CMD cp /build/layer/ruby/ruby/gems-3.2.0.zip /out/gems-3.2.0.zip
