name: Markdown Lint Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      # equivalent cli: markdownlint-cli2  "**/*.md" "#lambda/.aws-sam/**" "#.github/pull_request_template.md" "#.github/ISSUE_TEMPLATE/bug-or-feature-request.md" "#.github/instructions/**" --config .markdownlint.json
      - name: "Markdown Lint Check"
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23
        with:
          fix: false
          globs: |
            **/*.md
            !lambda/.aws-sam/**
            !.github/pull_request_template.md
            !.github/ISSUE_TEMPLATE/bug-or-feature-request.md
            !.github/instructions/**
